site_name: Octomatic Developers
site_author: Aurora Borealis Pvt. Ltd.
site_description: All the knowledge that is needed to integrate with Octomatic Enterprise API
pages:
  - Home: index.md
  - Architecture: Arconcepts.md
  - Starter Kit:
    - 'Starter Kit': StarterKit.md
    - 'iOS, APNS': iOSAPNSStarterKit.md
    - 'iOS, GCM' : iOSGCMStarterKit.md
    - 'android, native' : androidGCMStarterKit.md
    - 'android, cordova' : cordovaOctoStarterKit.md
  - 'API Doc' : ApiDoc.md
markdown_extensions:
    - toc:
        permalink: True
        separator: "_"
        baselevel: 1
        anchorlink: True
theme: yeti
use_directory_urls: False
html_navlinks: False
copyright: '&copy; 2016, <a href="http://www.octo.ai">Aurora Borealis</a><p />'
google_analytics: ['UA-76541897-2', 'developers.octo.ai']
